export const constants = {
  SHORT_MOVIES_DURATION: 40,
  INITIAL_MOVIES_CARDS_L: 12,
  INITIAL_MOVIES_CARDS_M: 8,
  INITIAL_MOVIES_CARDS_S: 5,
  ADD_MOVIES_CARDS_L: 3,
  ADD_MOVIES_CARDS_M: 2,
  ADD_MOVIES_CARDS_S: 1,
};
